language: java
sudo: required
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: qYXfVOPms7IbPSqFSqObR/2jOkBpNS69ygwRE2wiGarKfWyLSoBQWiVRn43p/UhPcfJJof5XRVPUkxqc64bvSHR2GusqgHzOe5/G41BsHXTGHkddY1UX2Jfm1FO3l1XKRoHYvHytDrHfNpSwL5lR0e0Dr5bn76RpB2inwhwhBFlSUq+x5jO0PDvRIYjG+XLlpwpMb6n9qeowozW9cw0lcGguRVB788WsiygJubP57U8D9GqKx/WNpGC6ibErCghK5K1iRXCja2ynSSgVD5N8WQZWmWSeu1EsLQaxlsT6a7oTzspduI1S8BYqQtHuVaw/smONKHQEe7O6TQJdbh5D+c2abBDHpPASK00Tkr/MnB+sUZKGUR+ZKTbsx+iAcZuSg11MoIu779JWqlHCT5tG1AGAZ26T3CQYv/OZ6OGwaux+FzBieVw/twRKyYI6uokBb/ElKAnoBeE1WoKUi2ZTNMxJhKNGfta1wyjqQy3uDIwvjsZ4O+ae7hZ30l4PxfvlWjITJwCfQl7Ei4s3wdu8RMaWb8nr6m7NCmPlVmxgTXwAaLHPm3tkyuMv6bh9EXEiUUewdAfRSXVaBjAJbyKzINoSQOzTfKkZEdgpSuRGvMG2PO1Cns+KbxuPcJXLd5vVOFeoltq5eA3B2l/9uGKV556zO3PCQf5ISrUhr5NPTqQ=
  - secure: mWI8tCQs33BhsVi63/61xwFau6ovCWR5io9NP3p76EniN6gK5BsH1aNBgDY1WL+Fh02Jr1vxtKgdzIUJNYDO30lx7SbmyRfFrsEmuD3FK3gzWdJ29a5USmb+01wPhuz5/wgdiJU5N93SAFN99/sHQqBGvB3lH4kE+5DGGDrHqXn+Fg6q3H0Os/+mkOi9eYnpfexEQGcM/VoTCt/quwBIdm2rZNY7MioyeoV7f6LkCZpQI58+cM7UlyNINu0HKoq8rlCrtrg/cArPPNNKMVU194wJVkszZ335FYnUqZDQ5HywDLtyjxeI4AvQEMlL8ll3szVsK/RVCE4dynO4laBbQRnOlNVkSiackppSrpJfSjSSnlkK1jM8SofW+sE7H7UMYTLExPW0DxbpYznsz/Ph/M1FATegvv/uf0ch8z7kNUbNKNkiAbz8eNP5Vj5p88I/+aWNzKSWuPttXn3CgHKIz9o8L8LEl7ZaNEvD1tuBg2QIHtQb1/p3qyC5Jq3AziZFXn8B5twFJdQNurX6562QQkesaRCUWasTlnSirl7CIR9kL6ojEeAnEKwQAbTyyYUJ9WkpRY+bgj12/iXfV4L57bofw+Tea+dUqfownJdX3aDkyXdGtZL0wf5tnC0fItGx+95vd9j0GGpXOSTfXVmMvPRmVeSAzP1mopEHWZrVdCs=
  - secure: RD4SHiu3CzDkUtXHg15QATRkMFVLhMgrtn8iGhTt7AoskZQmSh2oQlGJ+jtdwiWDNLy31Qd1t6e9VYgo3fh+MB703S7DGT3b36TScBU6hOqckKRJ0/i/LGPstMoSsRCMp7ac/8N/XbTE3XiULsFDCP8tDuhGeoAW3nr4fiie2SkAY2yq0H3uqXDrS2OxL57sayqh+k5ctzmJtsGesQKYw6sKPGPlsZQlcQrdYI2EZ4R+bbPTio7FFloFjqpQWVqS7BSvQeV527qUxNwCo0hGeBHcw+a4TkMai/ZzYiUSKrfFPJrvqWDp76gkC7TdBPesmoAnv4Ft0AggS5OHRT12wmspyh76UqhgtCS3tWJmm7ux330Nd8NXp+U70i4uffoo9NvLrMCFNJ5GnjJEP/g+8UNDWTz3ylDkuv3F6lZBw64zdmwX9AyKpZdMdU7aEwV+lI4VXGKcr7SOTLyCHUYJAALyC3I+yRR3EnuKCWx0g2cVb7KAdhNzv8/KDlJXcdMP1LMDvLCdtXXvbT1GU5ZAzOJx8G8pEEEb/VHxUIJmY+f6yyRqrsI+3oGxbQH3ewXbfk9nqpm8W4oCFgVqAr+rzfKp2C5TpJUEJfn6ItrcuK/pZYmKlTvXpmtguadbS3YO0/EEDC6dM8+Cuo/mU4evaE/FN/XTj0Ruy7RogBLxZYg=
before_install:
- mvn install:install-file -DgroupId=com.PDFjet -DartifactId=PDFjet -Dversion=1.0
  -Dfile=./lib/PDFjet-1.0.jar -Dpackaging=jar -DgeneratePom=true
- mvn install:install-file -DgroupId=com.javaplanner -DartifactId=javaplanner -Dversion=1.5
  -Dfile=./lib/javaplanner-1.5.jar -Dpackaging=jar -DgeneratePom=true
- export TZ=Pacific/Noumea
- git clone -b travis `git config --get remote.origin.url` target/travis
install: mvn install -DSkipTests=true -Dmaven.javadoc.skip=true -DcreateChecksum=true
  --settings target/travis/settings.xml
script:
- mvn test jacoco:report
after_success:
- mvn coveralls:report
before_deploy:
- export RELEASE_PKG_FILE=$(ls target/*.war)
- export RELEASE_PKG_MD5_FILE=$(ls target/*.war.md5)
- export RELEASE_PKG_SHA_FILE=$(ls target/*.war.sha1)
- echo "deploying $RELEASE_PKG_FILE , $RELEASE_PKG_MD5_FILE , $RELEASE_PKG_SHA_FILE
  to GitHub releases"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: CuK2E79eZZjpahlOwmrBDD5UanRQtdIjydSXreXFpp5HHHvjhXkK0cqJvqJ7oyOJIZgu4Z5feuXnnr8FgZimtL9ZEZBSMpijBnyM47818hBcr+l0DbEuneyXjmByG8uMxTI/PrQmu6GUJ4xfiQPxK+CrOIiOUQgVGfTWTq5+bxHbEMTH/XP3RW643C6EU6tSLLQ1Gu3pgfb6WOjAV1eRZCPtwLVmXHfdZElzkPQdoBmQf58+/PpoUc23+zC2X5GfEClpF+UgRmfEPaBG2xpQse62RNlQB3Odt1e2pR2aZ0kOd7BsW6EXSJCOVHz0AnUkMBxmEskIlCXq4LDf7CblS8iO778lmyZ9KIKQos9f/txgeKzIbciifGMtGml8zp6k931DHZUMcrCJX3lHPp4G03w/Zy3aE6JsAbrNUxgpN1cZaZDnyEgD6eGtX93zqi0WP9Zr8OvX1I2LpWXZV8knoVF3N3IvHB5KpH7CpdLGBT48SE9khysc8Z47M3S/o9Wa1olaQnbwwVTeq0QEfT6508HipLv/5CjOLYEcPsP4sXjy0rK+Su0EycXeRQQ9DIXPzEyKau4WGB8JT7stY1qosmwTc9pCVb1yVxYJupw1z9tP9O23tkGvX4urFxEB7cudmZV/Bj6elhbGdMogYLzqtrrTAPM0NjfNWQfRQopJiQo=
  file:
  - "${RELEASE_PKG_FILE}"
  - "${RELEASE_PKG_MD5_FILE}"
  - "${RELEASE_PKG_SHA_FILE}"
  on:
    tags: true
    repo: DSI-Ville-Noumea/sirh-kiosque-j2ee
notifications:
  slack:
    secure: G7pDgBransfKZZiq+sILwX5snjcHQVz+sRXPM13HZDoHMiJtxNxAQ5g+xc9GCROuqxgLYzxHE/E8lv36wRGL9SYV1/9GaYmpAYX4U0ItyyoEBh42C9uzLT9XLRjs+jssFLYEUmOEvS6uteOUfTSGVAPmiTSgitRwgJYJp+++KoxtbkxK47KU3Smu+QTSK2ojQf/ljCUqgIwhYSTgSmYOc+ly1kPc04imqyG2lufVs3ik7m0Z2ctuuNXVb7txef8vs1Z0MW12LF5Z3frfVES8lHZlT4q7n7zw5bOeN9+SWUF/qZ4J5/qdIYibWC75932dTNx2yxt1ksvNWDes3d6cUGhjfrHOY9rzm/7kY254v4a8KYRUEhsA9g8wcsBv2FkvUYNYngxhdVxio1wCUgWFPybYgWPlBYPW4COa4wiL811vljXZskAaXhNe1o0Cb2ugmvy71GdfK3vSCZpJpQ09c+fJmloI3cMvCW7bD99ya3QWosGgsmFyolMs0UNOGyI38piDvMwIurJwkL3bOyc1LSUx3DC0nTmeBRi0RqjpvEKYC8FoG7C78UEV2/jtWT2r8SugX2lHlnODyqpEAswXfspqbYIgAixITWBLaEzgxoem278ezBYNN8fCDzoa8n+GI7gJktTKWTWeeVgbdox9n6AWQi8yL4DX6bSzzrUxeRc=
